- 00-default/DEs-and-WMs/gdm.rules
- 00-default/DEs-and-WMs/gnome.rules
I was getting this, seeing if it helps:
```
Jan 09 18:07:06 kit kernel: sched: RT throttling activated
Jan 09 18:07:04 kit /usr/lib/gdm-wayland-session[1595]: 00:55:10.276 [ERROR] [wlr] [xwayland/selection/incoming.c:466] convert selection failed
Jan 09 18:07:04 kit /usr/lib/gdm-wayland-session[1595]: 00:55:10.276 [ERROR] [wlr] [xwayland/selection/incoming.c:466] convert selection failed
Jan 09 18:07:04 kit /usr/lib/gdm-wayland-session[1595]: 00:55:10.276 [ERROR] [wlr] [xwayland/selection/incoming.c:466] convert selection failed
Jan 09 18:07:04 kit /usr/lib/gdm-wayland-session[1595]: 00:55:10.276 [ERROR] [wlr] [xwayland/selection/incoming.c:466] convert selection failed
Jan 09 18:07:04 kit /usr/lib/gdm-wayland-session[1595]: 00:55:10.276 [ERROR] [wlr] [xwayland/selection/incoming.c:466] …
```
> Add rules for gdm wayland and a few gnome services

- 00-default/games/projectzomboid.rules
Before rule:
```
ps ax -o pid,ni,cmd | grep -i zomboid
...
6344   0 ./ProjectZomboid64
```
After rule:
```
ps ax -o pid,ni,cmd | grep -i zomboid
...
7179  -7 ./ProjectZomboid64
```
> games: Add Project Zomboid

- 00-default/games/openmw.rules
- 00-default/games/oxygennotincluded.rules
- 00-default/games/pathofbuilding.rules
Added OpenMW and Path of Building. Removed the duplicate of the native version of Oxygen Not Included. It is already in /00-default/games/steam-native.rules.
> Added new games and removed duplicate

- 00-default/games/quake.rules
- 00-default/games/steam-native.rules
- 00-default/games/wine_proton.rules
- 00-default/games/xonotic.rules
As the title says, adds new rules for Halo MCC and Terraria
Alongside, I have added ironwail to quake source port list, the linux native version of UT2004 and the executable of xonotic which you can get after compiling
> adds Halo MCC, and Terraria and many updates

- 00-default/games/wine_proton.rules
- the game's exe doesn't have a space in its name
> Update Cyberpunk 2077 in wine_proton.rules

- 00-default/games/gamescope.rules
I set it as type game since that seemed the most appropriate.
This sets gamescopes nice level properly while not stopping the steam overlay from functioning
> Works around https://github.com/ValveSoftware/gamescope/issues/107

- 00-default/Chats/chats.rules
adds a rule for vesktop(custom discord client with vencord)
> Add vesktop(alternative discord app) to chats.rules

- 00-default/DEs-and-WMs/hyprland.rules
- 00-default/DEs-and-WMs/sway.rules
- 00-default/Terminals/terminal.rules
- 00-default/nix.rules
- 00-default/waybar.rules
This PR mainly adds the equivalent PNAME of already added programs in NixOS.
- `+ hyprland-wrapped`
- `+ sway-wrapped`
- `+ waybar-wrapped`
- `+ kitty-wrapped`
Without these, the programs mentioned lag, when in high system load.
In addition, it also adds
- swaync - Sway notification daemon
- swayidle - Sway idle daemon
- nix lsp rules like nixd and nil
-  nom rules, equivalent of nix commands
along with their NixOS equivalent PNAMEs.
Since both [Chaotic-Nyx](https://github.com/chaotic-cx/nyx) and Nixpkgs provide ananicy-cpp-rules cachyos as a package, I am compelled to add the NixOS equivalent rules.
> Added rules for hyprland, sway, waybar, kitty and nix

- 00-default/compilers.rules
- 00-types.types
C and C++, Go, Java, and Rust compilers are added
Also added Bazel, Cmake, Ninja, and Meson build systems
> Add compilers.rules

- 00-default/games/ffxiv_dx11.rules
- 00-default/games/wine_proton.rules
This pull request adds in a rule for FFXIV. FFXIV is a fairly CPU Bound game and would benefit from having its NICE levels adjusted. This rule should work for both the Proton & XIVLauncher "Version" as the raw executable is the same.
> FFXIV Rule

- 00-default/games/wine_proton.rules
this commit removes the rule for "Terraria.bin.x86_64" in wine_proton.rules since it's the file for the native game and not the wine one(the rule is already present on steam-native.rules)
> remove native terraria from wine_proton.rules since it belongs to steam-native.rules

- 00-default/games/wine_proton.rules
Kingmaker has a Linux version but from what I could tell looking at SteamDB it runs the same executable. It is generally advised to run the Proton version however.
> Add Owlcat's Pathfinder games

- 00-default/games/steam-native.rules
- 00-default/games/wine_proton.rules
Added rules for the following games:
- Black Desert 
- EnderLilies Quietus of the Knights (both for native and through proton)
- GrimDawn
- Hades
- Throne and Liberty (BEWARE this can change on the official release)
- Othercide
- GranBlue Fantasy: Versus
And update the link on Guild Wars 2, linking it to the steampage
> Added games on wine_proton

- 00-default/games/wine_proton.rules
Adds rules for farlight 84, this time with both SolarlandClient.exe and SolarlandClient-Win64-Shipping.exe. 
However, I don't know if both should be included, existing rules for some Unreal Engine games like Atomic Heart seem to include both, while others like Grounded include only the *-Win64-Shipping.exe. Also, only the *-Win64-Shipping.exe seems to appear on the proccess monitor
> Farlight 84 rule

- 00-default/games/emulators.rules
This small PR just fixes the misspelled name for suyu game emulator.
> Fix: suyu process name incorrectly spelled as "suzu"

- 00-default/Terminals/terminal.rules
ptyxis terminal is default in Fedora 41 now
> Update terminal.rules - add ptyxis

- 00-default/games/wine_proton.rules
Pretty straight-forward, seems like the “#” got lost somewhere, causing an error in `ananicy-cpp` when reading the rules.
Resolves: #176
> Add Missing "#" on Comment

- 00-default/openscad.rules
OpenSCAD renders are a heavy CPU workload.
> Add OpenSCAD rules

- 00-default/DEs-and-WMs/gdm.rules
Gnome has removing realtime from mutter
because of problems with gnome-shell and gc's time
as the same time rt has bring some problems in gnome sessions like crash, now gnome not has more realtime for mutter and all dependents like gnome shell and even kms thread is not more running in rt
> gdm: Define service affinity

- 00-default/Chats/chats.rules
- 00-default/DEs-and-WMs/hyprland.rules
- 00-default/DEs-and-WMs/sway.rules
- 00-default/DEs-and-WMs/waybar.rules
- 00-default/Services/gvfs.rules
- 00-default/Terminals/terminal.rules
- 00-default/nix.rules
- 00-default/widget-manager.rules
There's a patch applied to ananicy-cpp that automatically finds wrappers
> Remove NixOS-specific rules

- 00-default/games/luanti.rules
The Minetest developers have renamed their game to Luanti, details in [this blog post](https://blog.luanti.org/2024/10/13/Introducing-Our-New-Name).
Therefore, I have added a new rule to support Luanti.
An example of Luanti's process:
```
ps -A | grep luanti
54034 ?         00:00:00 luanti
```
The rule for Minetest is still kept for those who still use the `minetest` command to run the game.
> Add rule for Luanti (formerly Minetest)

- 00-default/Browsers/browsers.rules
- 00-default/Chats/chats.rules
The process names for Zen Browser and Betterbird installed via Flatpak are `zen` and `betterbird-bin`.
```text
$ ps -Ae | grep zen
30378 ?        00:43:50 zen
84370 ?        00:04:01 zen
```
```text
$ ps -Ae | grep betterbird
87265 ?        00:00:09 betterbird-bin
```
> Expand rules for Zen Browser and Betterbird

- 00-default/games/luanti.rules
The process name for Luanti installed via Flatpak is `luanti.bin`.
```text
$ ps -A | grep luanti
46442 pts/1    00:00:01 luanti.bin
```
> Expand rules for Luanti

- 00-default/Services/sshd.rules
For some reason `sshd` wasn't already in here?
> Add sshd rule

- 00-default/Services/kubo.rules
The kubo daemon can pretty safely be set as a background process
> Add kubo rules

- 00-default/games/steam-native.rules
- 00-default/games/wine_proton.rules
The process names look a little strange at first glance but I did double check and verify that "Hollow Knight Silksong" and "Hollow Knight S" were the process names for the native version and the proton version respectively.
> Add rules for Hollow Knight: Silksong (both native and Proton)
