00-default/games/assassinscreed.rules, 00-default/games/deathstranding.rules, 00-default/games/thelastofus.rules
The Last of Us - Part 1, Death Stranding, AC Valhalla.
=> Adding some games that were missing.

00-default/games/arma3.rules, 00-default/games/battlebit.rules, 00-default/games/dayz.rules, 00-default/games/deeprockgalactic.rules, 00-default/games/squad.rules, 00-default/games/warthunder.rules
Added Arma3, Battlebit, Dayz, Deep Rock Galactic, Squad and War thunder
=> Adding a few games 

00-default/DEs-and-WMs/compton.rules, 00-default/DEs-and-WMs/plank.rules, 00-default/DEs-and-WMs/sxhkd.rules, 00-default/compton.rules, 00-default/dukenukem.rules, 00-default/games/DOOM.rules, 00-default/games/doom64.rules, 00-default/lightdm.rules, 00-default/plank.rules, 00-default/rsync.rules, 00-default/tools/7z.rules, 00-default/weston.rules, 00-default/xmonad.rules
chore(rules): fix typos
dedupe(doom): move doom64.rules to DOOM.rules and remove doom64.rules
=> dedupe(rules): remove duplicates

00-default/games/dayz.rules
missed the exe in the dayz executable
=> Fix dayz rule

00-default/Audio-Video/audioserver.rules
pipewire-pulse is pulseaudio emulation under pipewire, so prioritize
=> add pipewire-pulse

00-default/games/oxygennotincluded.rules, 00-default/games/pathofexile.rules
Added games Path of Exile and Oxygen Not Included
=> Added games Path of Exile and Oxygen Not Included

00-default/games/littlewitchnobeta.rules, 00-default/games/mixolumia.rules, 00-default/games/streetfighter.rules, 00-default/games/yetanotherzombiesurvivors.rules
Little Witch Nobeta
Mixolumia
Street Fighter 6
Yet Another Zombie Survivors
=> Add more game rules

00-default/games/wasteland.rules
=> Further game rules for:

00-default/games/PES2013.rules
=> Pro Evo Soccer 2013 Rules

00-default/games/PES.rules
Make it a rules file for more PES games
=> Update and rename PES2013.rules to PES.rules and add PES6 Rules

00-default/games/armoredcore.rules, 00-default/games/brotato.rules, 00-default/games/stray.rules
Added the following:
* ARMORED CORE VI FIRES OF RUBICON
* Brotato
* Stray
=> More game rules

00-default/games/insurgency.rules
=> Added Insurgency Sandstorm

00-default/Browsers/browsers.rules
Reorganise browser configurations alphabetically and categorically & add Mercury browser
=> Reorganise browser configurations alphabetically and categorically & add Mercury browser

00-default/games/Demonologist.rules, 00-default/games/DiktapunkCelebrityCombat.rules, 00-default/games/ParanormalHK.rules, 00-default/games/SexChess.rules, 00-default/games/TheOutlastTrials.rules, 00-default/games/cs2.rules, 00-default/games/garrysmod.rules, 00-default/games/phasmophobia.rules, 00-default/games/steam-native.rules
New games:
- Demonologist
- Diktapunk / Celebrity Kombat
- Dying Light
- Jabroni Brawl: Episode 3
- NSFW Solitaire
- ParanormalHK
- Phasmophobia
- Sex Chess
- The Outlast Trials
- Zombie Panic: Source
Moved "cs2" under CSGO and removed duplicates;
Moved Gmod to steam-native.rules;
Fixed commented links in steam-native.
=> New games, fixes

00-default/games/wine_proton.rules
a bit of a small pr for a game I quite enjoy
=> Add Omega Strikers

00-default/Audio-Video/haruna.rules
Haruna is a media player for KDE Plasma.
=> add Haruna media player

00-default/Audio-Video/tidal-hifi.rules
TIDAL is an artist-first, fan-centered music streaming platform that delivers over 100 million songs in HiFi sound quality to the global music community.
=> Add tidal-hifi.rules

00-default/screenshotter.rules, 00-default/shutter.rules
This PR adds screenshotter.rules, that contains:
- flameshot
- grim
- slurp
- swappy
- xfce-screenshotter
Also merged shutter.rules into a single screenshotter.rules.
=> Add screenshotter.rules

00-default/Services/gvfs.rules, 00-default/Services/misc-services.rules, 00-default/Services/speech-dispatcher.rules, 00-default/android-studio.rules, 00-default/cava.rules, 00-default/clangd.rules, 00-default/nix.rules
- [Add clangd.rules](https://github.com/CachyOS/ananicy-rules/commit/c1a0b2c0a0d38a9e17ac644e3c433c15e12ea9e3)
- [Update android-studio.rules](https://github.com/CachyOS/ananicy-rules/commit/54ba43d4e7d6f56e5a87d574bfa8213da5776d44)
- [Add cava.rules](https://github.com/CachyOS/ananicy-rules/commit/be8745652ba389545bc24ef57a927cc515e5f2f9)
- [gvfs.rules: add .gvfsd-metadata subprocess](https://github.com/CachyOS/ananicy-rules/commit/bf0dbb75a10a715024298fe90b695ff520fbee60)
- [misc-services: added bubblewrap, fsnotifier](https://github.com/CachyOS/ananicy-rules/commit/3da0c9b7846144808ee593fd7c5fcdf3cb56188a)
- [nix.rules: add nixpkgs-review, nh, nom, nixd rules](https://github.com/CachyOS/ananicy-rules/commit/1c109a5ff32b38818ec46b7721dcb9ad509c77a0)
- [Add …
=> Add clangd, cava, bubblewrap and fsnotifier, update android-studio, gvfs, nix rules

00-default/DEs-and-WMs/gnome.rules, 00-default/DEs-and-WMs/hyprland.rules, 00-default/Services/gvfs.rules, 00-default/Services/speech-services.rules, 00-default/deluge.rules, 00-default/libreoffice.rules, 00-default/swww.rules, 00-default/tools/btop.rules, 00-default/tools/htop.rules, 00-default/tools/system-monitoring.rules, 00-default/widget-manager.rules
- [system-monitoring.rules: add nvtop and gnome-system-monitor](https://github.com/CachyOS/ananicy-rules/commit/d78bb82486cdbb05ca683e5bcca3af6bc166c221)
- [speech-services.rules: add mbrola service](https://github.com/CachyOS/ananicy-rules/commit/dd488af030798bb25a84acdfff92f7d0fc642f96)
- [gvfs.rules: add dnssd, netword, trash subprocesses](https://github.com/CachyOS/ananicy-rules/commit/e21b296d8e1c81619a35cbadbf5e7f5c04eac77b)
- [libreoffice.rules: add soffice process](https://github.com/CachyOS/ananicy-rules/commit/6598d16a82babcca2e4e78c5bb51833daba7694e)
- [add swww.rules](https://github.com/CachyOS/ananicy-rules/commit/43cf0c49711087926c2ccf6419f2ab026cd003d0)
- [widget-manager.rules: add ags, rofi, wofi](https://github.com/CachyOS/ananicy-rules/commit/d3de982730fddfe5d7207a1f37462 …
=> Add gnome-system-monitor, widget-managers, various services rules, update deluge, libreoffice

00-default/games/steam-native.rules
List all rules alphabetically, remove duplicates.
=> Reorganize steam-native.rules

00-default/games/wine_proton.rules
Adding "The Finals" ananicy rule
=> Update wine_proton.rules for THE FINALS

00-default/games/wine_proton.rules
Ghost of Tsushima - DIRECTOR'S CUT
=> Add Ghost of Tsushima

00-default/Browsers/browsers.rules
Adds the Firefox-based Webbrowser Floorp.
=> Add Floorp Browser

00-default/DEs-and-WMs/gnome.rules, 00-default/games/wine_proton.rules
Adding ForzaHorizon5 & mutter-x11-frames.
=> Game & DE stuff

00-default/Browsers/browsers.rules
Firefox but with vertical tabs :)
https://zen-browser.app/
=> Add zen browser

00-default/Chats/chats.rules
A telegram client with some nifty features :)
https://64gr.am/
=> Add 64gram telegram client

00-default/games/wine_proton.rules
Tested with log_applied_rule = true.
=> Add Black Myth: Wukong and TCG Card Shop Simulator

00-default/games/sober.rules
=> Add Sober to games

00-default/Audio-Video/miru.rules, 00-default/VPN/hummingbird.rules, 00-default/games/eaorigin.rules, 00-default/games/launchers.rules, 00-default/games/wine_proton.rules
https://github.com/CachyOS/ananicy-rules/issues/135
=> rm Duplicate rules

00-default/games/wine_proton.rules
=> Add Against the Storm

00-default/tools/chrony.rules
Add [chrony](https://chrony-project.org/)
=> Add chrony

00-default/tools/auto-cpufreq.rules
Add [auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq)
=> Add auto-cpufreq

00-default/games/steam-native.rules, 00-default/games/wine_proton.rules
Add STALKER 2 and Hobo: Tough Life (proton and native)
=> Add STALKER 2 and Hobo: Tough Life

00-default/Audio-Video/audacity.rules, 00-default/Audio-Video/ncmpcpp.rules, 00-default/Audio-Video/obs-studio.rules, 00-default/Audio-Video/spotify.rules, 00-default/Chats/chats.rules, 00-default/Services/polkit.rules, 00-default/gammastep.rules, 00-default/imv.rules, 00-default/libreoffice.rules
sorry if I have been updating alot with these changes, but i am also enjoying adding some stuffs lately. :]
you may now close this [issue](https://github.com/CachyOS/ananicy-rules/issues/140) since I added spotube.
=> add polkit-agents, imv, tenacity, spotube and betterbird, and update gammastep, ncmpcpp, obs-studio and libreoffice

00-default/games/etterna.rules
Fix etterna.rules causing error on ananicy start because of type is not correctly quoted
=> fix(rules): Quote type correctly

00-default/games/wine_proton.rules
- add Star Wars: Battlefront II
=> Star Wars: Battlefront II

00-default/games/wine_proton.rules
Added link for Path Of Exile 2 next to Path Of Exile 1, as both use the same executables. Hope that's ok.
=> Added RAGE 2, ULTRAKILL, RoboCop: Rouge City and updated Path of Exile

00-default/blender.rules, 00-default/tools/ffmpeg.rules, 00-default/videoeditors.rules
Currently, I've added ffmpeg, blender3d, and davinci resolve (NLE video editing software).
Side note: I just realized the file structure is a bit messy now. *Would* it be okay to open a PR just to reorganize it? Further discussion might be needed, tho
=> feat: add a few program related to render

00-default/Chats/chats.rules
Add some of the most used clients listed in https://matrix.org/ecosystem/clients/
Tell me if I spell the binary names wrong or there are more to be added.
=> feat: add matrix clients

00-default/Services/firewalld.rules
Idk if is better to use service instead, but if is a firewall the better niceness
will be RT for better preemption?
=> rules: Introduce firewalld service rules

00-default/Services/amazon-cloudwatch-agent.rules
Okay I don't blame you for not already having this one
=> Add amazon-cloudwatch-agent rule

00-default/games/wine_proton.rules
As the title state, this adds ananicy rules for Sonic X Shadow Generations executables
=> Add rule for Sonic X Shadow Generations
